---
- name: node-backup | exporter | remove the cache file
  ansible.builtin.file:
    path: "{{ _node_backup_exporter_cache_file }}"
    state: absent
  notify: restart node-backup exporter
  when: node_backup_wipe_cache_enable | bool

- name: node-backup | exporter | copy exporter file
  ansible.builtin.copy:
    src: exporter.py
    dest: "{{ _node_backup_exporter_file }}"
    mode: "0755"
    owner: "{{ node_backup_user }}"
    group: "{{ node_backup_user }}"
  notify: restart node-backup exporter

- name: node-backup | exporter | copy exporter systemd unit file
  ansible.builtin.template:
    src: node-backup-exporter.service.j2
    dest: /etc/systemd/system/node-backup-exporter.service
    owner: root
    group: root
    mode: "0644"
  notify: restart node-backup exporter

# to avoid 2 restarts during the first deploy
- name: node-backup | exporter | flush handlers
  ansible.builtin.meta: flush_handlers

- name: node-backup | exporter | start exporter service
  ansible.builtin.systemd:
    name: node-backup-exporter
    state: started
    enabled: true
    daemon_reload: true
