---
## Molecule
ansible_user: root

## node
node_role: "validator"
node_user: polkadot
node_chain: westend-local
node_chain_backup_chain_path: "westend_local_testnet"
node_chain_backup_restoring_type: none
node_parachain_chain_backup_restoring_type: none
node_p2p_bind_addr: "127.0.0.1"
node_ansible_annotation_path: /tmp/substrate.prom
node_binary_version: v1.12.0
node_binary: "https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-{{ node_binary_version }}/polkadot"
node_prepare_worker_binary: "https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-{{ node_binary_version }}/polkadot-prepare-worker"
node_execute_worker_binary: "https://github.com/paritytech/polkadot-sdk/releases/download/polkadot-{{ node_binary_version }}/polkadot-execute-worker"


# node_backup
_gcp_bucket: test-blockstore-backups
node_backup_user: polkadot
node_backup_r2_access_key_id: abc
node_backup_r2_secret_access_key: cba
node_backup_r2_api_url: https://a.b
node_backup_targets:
  - service_name: alice-rocksdb-prune
    local_path: /opt/alice-rocksdb-prune/chains/{{ node_chain_backup_chain_path }}/db
    rpc_port: 9933
    bucket_name: "{{ _gcp_bucket }}"
    type: gcp-rclone
  - service_name: bob-paritydb-prune
    local_path: /opt/bob-paritydb-prune/chains/{{ node_chain_backup_chain_path }}/paritydb
    rpc_port: 9934
    bucket_name: "{{ _gcp_bucket }}"
    type: r2-rclone
    bucket_domain: c.d
