loki_download_url: https://github.com/grafana/loki/releases/download/v2.1.0/loki-linux-amd64.zip
loki_binary_path: /usr/local/bin/loki-linux-amd64
# binary will only be downloaded if not existant
# this can be changed here
loki_refresh_binary: no
loki_data_dir: /var/lib/loki
loki_config_path: /etc/loki/loki.yaml
loki_alerting_rules_path: /etc/loki/rules
loki_retention_period: 672h # 4 weeks
