---

- name: Post tasks | Remove temporary directory
  ansible.builtin.file:
    path: "{{ _node_temp_dir.path }}"
    state: absent
  check_mode: false
  changed_when: false
  when: _node_temp_dir.path is defined
