---

- name: node | Tests
  ansible.builtin.include_tasks:
    file: 100-tests.yml
    apply:
      tags: ['node', 'node-tests']
  tags: ['node', 'node-tests']

- name: node | Check the systemd unit file exists
  ansible.builtin.stat:
    path: "{{ _node_unit_file }}"
  register: _node_systemd_unit_file_stat
  tags: ['node', 'node-systemd', 'node-binary', 'node-chain', 'node-restart', 'node-wipe', 'node-restore-chain']

- name: node | Prepare
  ansible.builtin.include_tasks:
    file: 200-prepare.yml
    apply:
      tags: ['node', 'node-prepare']
  tags: ['node', 'node-prepare']

- name: node | Wipe
  ansible.builtin.include_tasks:
    file: 300-wipe.yml
    apply:
      tags: ['node', 'node-wipe']
  when: node_db_wipe | bool or node_parachain_db_wipe | bool
  tags: ['node', 'node-wipe']

# It will only be run if the systemd service state is 'running'.
# It should help to avoid the situation when we try to update a broken node.
- name: node | Check the node state before deploying
  ansible.builtin.include_tasks:
    file: 001-health-check.yml
    apply:
      tags: ['node', 'node-health-check']
  vars:
    _node_pre_check: true
  tags: ['node', 'node-health-check', 'node-restore-chain']

- name: node | Binary
  ansible.builtin.include_tasks:
    file: 400-binary.yml
    apply:
      tags: ['node', 'node-binary']
  when: node_binary_deployment | bool
  tags: ['node', 'node-binary']

- name: node | Memory profiler
  ansible.builtin.include_tasks:
    file: 500-memory-profiler.yml
    apply:
      tags: ['node', 'node-memory-profiler']
  when: node_memory_profiler_enable | bool
  tags: ['node', 'node-memory-profiler']

- name: node | Chain
  ansible.builtin.include_tasks:
    file: 600-chain.yml
    apply:
      tags: ['node', 'node-chain']
  when: node_chain_deployment | bool
  tags: ['node', 'node-chain']

- name: node | Set restore variables (chain id)
  ansible.builtin.include_tasks:
    file: 700-get-chainid.yml
    apply:
      tags: ['node', 'node-restore-chain']
  when: _node_restore_relaychain or _node_restore_parachain
  tags: ['node', 'node-restore-chain']

- name: node | Set restore variables 1
  ansible.builtin.set_fact:
    _node_restore_list: "{{ _node_restore_list + [_node_chain_backup_data] }}"
  when: _node_restore_relaychain
  tags: ['node', 'node-restore-chain']

- name: node | Set restore variables 2
  ansible.builtin.set_fact:
    _node_restore_list: "{{ _node_restore_list + [_node_parachain_chain_backup_data] }}"
  when: _node_restore_parachain
  tags: ['node', 'node-restore-chain']

- name: node | Restore chain
  ansible.builtin.include_tasks:
    file: 800-restore-chain.yml
    apply:
      tags: ['node', 'node-restore-chain']
  loop: "{{ _node_restore_list }}"
  tags: ['node', 'node-restore-chain']

- name: node | Systemd
  ansible.builtin.include_tasks:
    file: 900-systemd.yml
    apply:
      tags: ['node', 'node-systemd']
  when: node_systemd_deployment | bool
  tags: ['node', 'node-systemd']

- name: node | Restart
  ansible.builtin.include_tasks:
    file: 002-restart.yml
    apply:
      tags: ['node', 'node-restart']
  when: node_force_restart | bool
  tags: ['node', 'node-restart']
