---
dependency:
  name: galaxy
driver:
  name: ${DRIVER:-docker}
platforms:
  - name: instance
    # LXD
    source:
      alias: debian/bullseye/amd64
    # DOCKER
    image: "docker.io/paritytech/debian10:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    # need this for systemctl work
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    # to pull image  from docker hub uncomment this
    pre_build_image: true

verifier:
  name: ansible
  options:
    D: True
lint: |
  set -e
  yamllint .
  ansible-lint