## Molecule
ansible_user: root

## node
node_binary_version: "v0.9.42"
node_user: "polkadot"
node_binary: "https://github.com/paritytech/polkadot/releases/download/{{ node_binary_version }}/polkadot"
node_chain: rococo-local
node_chain_backup_restoring_type: "none"
node_parachain_chain_backup_restoring_type: "none"
node_ansible_annotation_path: "/tmp/substrate.prom"

## ws_health_exporter
ws_health_exporter_user: "{{ node_user }}"
ws_health_exporter_log_level: "DEBUG"
ws_health_exporter_port: 8001
ws_health_exporter_node_max_unsynchronized_block_drift: 2
ws_health_exporter_node_min_peers: 1

ws_health_exporter_ws_urls:
  - "ws://127.0.0.1:9944"
  - "ws://127.0.0.1:9945"
