on:
  workflow_call:
    inputs:
      role-path:
        required: true
        type: string
      molecule-driver:
        required: true
        type: string
jobs:
  molecule:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    env:
      DRIVER: ${{ inputs.molecule-driver }}
    steps:
      - run: git config --global --add safe.directory "${{ github.repository }}"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Setup Python modules
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Setup LXD
        if: ${{ inputs.molecule-driver == 'lxd' }}
        uses: canonical/setup-lxd@v0.1.1 # https://github.com/canonical/setup-lxd
        with:
          channel: latest/stable
      - name: Setup Python modules
        run: pip3 install yamllint ansible ansible-lint molecule molecule-plugins[docker] molecule-lxd docker
      - name: Run molecule
        run: molecule test --all
        working-directory: "${{ github.repository }}/${{ inputs.role-path }}"
