name: check common collection Galaxy version

on:
  pull_request:
    paths:
      - 'common/**'

jobs:
  check-version:
    uses: ./.github/workflows/reusable-check-version.yml
    with:
      collection-name: common
