name: check PR (key_inject)

on:
  pull_request:
    paths:
      - roles/key_inject/**
      - .github/**

jobs:
  run-molecule-tests:
    strategy:
      fail-fast: false
      matrix:
        molecule-driver: [docker]
    uses: ./.github/workflows/reusable-molecule.yml
    with:
      role-name: key_inject
      molecule-driver: ${{ matrix.molecule-driver }}